version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: project
    ports:
      - "3308:3306"
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
